spring:
  datasource:
    url: jdbc:h2:mem:D:\develop\h2\myDatabase;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: root
    password: 813552168
    schema:
      - classpath:sql/schema.sql
    data:
      - classpath:sql/initInsert.sql
  thymeleaf:
    #mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
mybatis:
  type-aliases-package: com.example.demo.pojo
